name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_TOKEN }}
          publish_branch: gh-pages  # 推送到当前 gh-pages 分支
          publish_dir: ./public # 推送生成的public文件下的内容到 gh-pages 分支
          commit_message: ${{ github.event.head_commit.message }}
# 开始部署到VPS上的工作流
      - name: Cache Private Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.BLOG_DEPLOY_KEY }}
      - name: Scan public keys
        run: ssh-keyscan zling.site >> ~/.ssh/known_hosts
      - name: Deploy
        run: rsync -av --delete ./public ubuntu@zling.site:/data/caddy/site/hugo-web